# Generated by Django 4.1 on 2023-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testreference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
