# Generated by Django 4.1 on 2023-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_alter_test_id_alter_testreference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreference',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='test_images'),
        ),
    ]
