# Generated by Django 4.1 on 2023-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_testreference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreference',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='storage/images'),
        ),
    ]
